# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development: 
  adapter: postgresql
  pool: 5
  timeout: 5000
  database: kwik_development

production:
  adapter: postgresql
  encoding: unicode
  database: kwik_development
  pool: 5


test:
  adapter: postgresql
  encoding: unicode
  database: kwik_test
  pool: 5


default: &default
      adapter: postgresql
      encoding: unicode
      pool: 5
      timeout: 5000
